Update Packages-AutoBuild.yml

diff --git a/.github/workflows/Packages-AutoBuild.yml b/.github/workflows/Packages-AutoBuild.yml
--- a/.github/workflows/Packages-AutoBuild.yml
+++ b/.github/workflows/Packages-AutoBuild.yml
@@ -208,7 +208,7 @@ jobs:
               mv feeds/packages/lang.b feeds/packages/lang
               [ "$(grep "PKG_BUILD_DEPENDS" package/feeds/kiddin9/$ipk/Makefile)" ] || mv feeds/packages/lang/node feeds/packages/lang/node.b
              fi
-             make package/$ipk/compile -j$(($(nproc)+1)) V=s 2>&1 | tee error_$ipk.log | grep -i error || true
+             [ "$(make package/$ipk/compile -j$(($(nproc)+1)) V=s 2>&1 | tee error_$ipk.log | grep -i "Error 2" || true)" ] || rm -rf error_$ipk.log
              if [[ $ipk != luci-* ]]; then
               mv -f feeds/packages/lang feeds/packages/lang.b 2>/dev/null || true
               mv -f feeds/packages/lang.b/node.b feeds/packages/lang.b/node 2>/dev/null || true
